### ISSUE TITLE
NumberBox Mode does not work

### ISSUE THREAD

**Issue by ghost1372** [marcelwgn/PagerControlPolyfill#1]
Hi, tnx for this great control
I tested a little and it seems that there is some issues:

changing DisplayMode in Runtime crash app
```
<muxc:PagerControl DisplayMode="ButtonPanel"/>
```
![image](https://github.com/marcelwgn/PagerControlPolyfill/assets/9213496/5fbe52a9-450d-4f4f-a2d2-42bcc1988419)

changing DisplayMode to NumberBox does not do anything
![xx](https://github.com/marcelwgn/PagerControlPolyfill/assets/9213496/c3351d08-22f1-41ab-a0df-8728ffd38363)

**Comment by marcelwgn** [comment]
Thank you for creating this issue. Unfortunately, I'm unable to reproduce the crash, could you please show the code you used to get the app to crash or attach a repro project?

Regarding numberbox not working, this was a mistake on my end. Version 1.0.1 is out now that has the fix for this.

**Comment by ghost1372** [comment]
thank you, both issue fixed.
