### ISSUE TITLE
confuse between new page index and previous index on SelectedIndexChanged event

### ISSUE THREAD

**Issue by jingliancui** [marcelwgn/PagerControlPolyfill#2]
<img width="705" alt="image" src="https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/97167ebd-0a1a-40e0-93e0-3f38f6337806">

<img width="415" alt="image" src="https://github.com/marcelwgn/PagerControlPolyfill/assets/16309962/594b7a88-f4d2-4ae6-946a-500325d2d498">

**Comment by marcelwgn** [comment]
Thank you for reporting this issue, this is fixed with dd6bfd3, which is currently pending on NuGet and should be available in the next hour or so.
